version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: jd_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - jd_network
        depends_on:
            - db
    web:
        image: nginx:alpine
        container_name: jd_web
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - jd_network
        depends_on:
            - app
    db:
        image: mysql:8.0
        container_name: jd_db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: jd_technology
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - jd_network
networks:
    jd_network:
        driver: bridge
volumes:
    db_data:
